package com.bupt.app.auth.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_user_info.id
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_user_info.loginName
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_user_info.name
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_user_info.password
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_user_info.companyId
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    private Integer companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_user_info.departmentId
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    private Integer departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_user_info.isManager
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    private Integer ismanager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_auth_user_info.hireDate
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    private Date hiredate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_user_info.id
     *
     * @return the value of tb_auth_user_info.id
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_user_info.id
     *
     * @param id the value for tb_auth_user_info.id
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_user_info.loginName
     *
     * @return the value of tb_auth_user_info.loginName
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_user_info.loginName
     *
     * @param loginname the value for tb_auth_user_info.loginName
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_user_info.name
     *
     * @return the value of tb_auth_user_info.name
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_user_info.name
     *
     * @param name the value for tb_auth_user_info.name
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_user_info.password
     *
     * @return the value of tb_auth_user_info.password
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_user_info.password
     *
     * @param password the value for tb_auth_user_info.password
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_user_info.companyId
     *
     * @return the value of tb_auth_user_info.companyId
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_user_info.companyId
     *
     * @param companyid the value for tb_auth_user_info.companyId
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_user_info.departmentId
     *
     * @return the value of tb_auth_user_info.departmentId
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_user_info.departmentId
     *
     * @param departmentid the value for tb_auth_user_info.departmentId
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_user_info.isManager
     *
     * @return the value of tb_auth_user_info.isManager
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public Integer getIsmanager() {
        return ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_user_info.isManager
     *
     * @param ismanager the value for tb_auth_user_info.isManager
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public void setIsmanager(Integer ismanager) {
        this.ismanager = ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_auth_user_info.hireDate
     *
     * @return the value of tb_auth_user_info.hireDate
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_auth_user_info.hireDate
     *
     * @param hiredate the value for tb_auth_user_info.hireDate
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

	@Override
	public String toString() {
		return "User [id=" + id + ", loginname=" + loginname + ", name=" + name
				+ ", password=" + password + ", companyid=" + companyid
				+ ", departmentid=" + departmentid + ", ismanager=" + ismanager
				+ ", hiredate=" + hiredate + "]";
	}
    
    
}