package com.bupt.app.auth.dao;

import com.bupt.app.auth.model.User;
import com.bupt.app.auth.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_user_info
     *
     * @mbggenerated Mon Jun 24 23:44:25 CST 2013
     */
    int updateByPrimaryKey(User record);
}